name: Feature request
description: Propose a user need and possible approach
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed direction
